server {
    listen 80;
    listen [::]:80;
    server_name apt.winegui.melroy.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name apt.winegui.melroy.org;

    root /var/www/apt.winegui.melroy.org/html;
    autoindex off;
    disable_symlinks on;

    ssl_certificate /etc/letsencrypt/live/apt.winegui.melroy.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apt.winegui.melroy.org/privkey.pem;

    location / {
        limit_except GET HEAD { deny all; }
        try_files $uri =404;
    }

    location ~ /\. {
        deny all;
    }

    add_header X-Content-Type-Options nosniff always;
}
